name: harry_potter_sorting_flutter
description: "A Harry Potter Magic Sorting Hat application in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  auto_route: ^9.3.0+1
  provider: ^6.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  drift_dev: ^2.24.0
  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/house_crests/

  fonts:
    - family: HarryP
      fonts:
        - asset: fonts/harry_p.ttf
